name: Sanity Check

on:
  pull_request:
  push:
    branches: [main]
  workflow_dispatch:

    
permissions:
  contents: read
  pull-requests: write
  issues: write

jobs:
  test-basic:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: Test Action
        uses: Surabhis12/sanity-check-action@release/v1.1.0  # Your branch
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}